-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 12:10:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wikipedie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wikipedie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wikipedie` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `wikipedie` ;

-- -----------------------------------------------------
-- Table `wikipedie`.`stranka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedie`.`stranka` (
  `idStranka` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  `datum_vytvoreni` DATE NOT NULL,
  PRIMARY KEY (`idStranka`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikipedie`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedie`.`kategorie` (
  `idKategorie` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  `popis` TEXT NULL,
  PRIMARY KEY (`idKategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikipedie`.`uzivatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedie`.`uzivatel` (
  `idUzivatel` INT NOT NULL AUTO_INCREMENT,
  `krestni_jmeno` INT NOT NULL,
  `prijmeni` VARCHAR(255) NOT NULL,
  `heslo` VARCHAR(255) NOT NULL,
  `datumRegistrace` DATE NOT NULL,
  PRIMARY KEY (`idUzivatel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikipedie`.`historie_editace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedie`.`historie_editace` (
  `idHistorie_editace` INT NOT NULL AUTO_INCREMENT,
  `verze` INT NOT NULL,
  `popis_editace` TEXT NOT NULL,
  `datum_editace` DATE NOT NULL,
  `stranka_idStranka` INT NOT NULL,
  `obsah` TEXT NOT NULL,
  `uzivatel_idUzivatel` INT NOT NULL,
  PRIMARY KEY (`idHistorie_editace`),
  INDEX `fk_historie_editaci_stranka1_idx` (`stranka_idStranka` ASC),
  INDEX `fk_historie_editace_uzivatel1_idx` (`uzivatel_idUzivatel` ASC),
  CONSTRAINT `fk_historie_editaci_stranka1`
    FOREIGN KEY (`stranka_idStranka`)
    REFERENCES `wikipedie`.`stranka` (`idStranka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historie_editace_uzivatel1`
    FOREIGN KEY (`uzivatel_idUzivatel`)
    REFERENCES `wikipedie`.`uzivatel` (`idUzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikipedie`.`obrazek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedie`.`obrazek` (
  `idObrazek` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idObrazek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikipedie`.`diskuse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedie`.`diskuse` (
  `idDiskuse` INT NOT NULL AUTO_INCREMENT,
  `obsah` TEXT NULL,
  `datum` DATE NOT NULL,
  `stranka_idStranka` INT NOT NULL,
  `uzivatel_idUzivatel` INT NOT NULL,
  PRIMARY KEY (`idDiskuse`),
  INDEX `fk_diskuse_stranka1_idx` (`stranka_idStranka` ASC),
  INDEX `fk_diskuse_uzivatel1_idx` (`uzivatel_idUzivatel` ASC),
  CONSTRAINT `fk_diskuse_stranka1`
    FOREIGN KEY (`stranka_idStranka`)
    REFERENCES `wikipedie`.`stranka` (`idStranka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diskuse_uzivatel1`
    FOREIGN KEY (`uzivatel_idUzivatel`)
    REFERENCES `wikipedie`.`uzivatel` (`idUzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikipedie`.`stranka_has_kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedie`.`stranka_has_kategorie` (
  `stranka_idStranka` INT NOT NULL,
  `kategorie_idKategorie` INT NOT NULL,
  PRIMARY KEY (`stranka_idStranka`, `kategorie_idKategorie`),
  INDEX `fk_stranka_has_kategorie_kategorie1_idx` (`kategorie_idKategorie` ASC),
  INDEX `fk_stranka_has_kategorie_stranka1_idx` (`stranka_idStranka` ASC),
  CONSTRAINT `fk_stranka_has_kategorie_stranka1`
    FOREIGN KEY (`stranka_idStranka`)
    REFERENCES `wikipedie`.`stranka` (`idStranka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stranka_has_kategorie_kategorie1`
    FOREIGN KEY (`kategorie_idKategorie`)
    REFERENCES `wikipedie`.`kategorie` (`idKategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikipedie`.`obrazek_has_stranka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wikipedie`.`obrazek_has_stranka` (
  `obrazek_idObrazek` INT NOT NULL,
  `stranka_idStranka` INT NOT NULL,
  PRIMARY KEY (`obrazek_idObrazek`, `stranka_idStranka`),
  INDEX `fk_obrazek_has_stranka_stranka1_idx` (`stranka_idStranka` ASC),
  INDEX `fk_obrazek_has_stranka_obrazek1_idx` (`obrazek_idObrazek` ASC),
  CONSTRAINT `fk_obrazek_has_stranka_obrazek1`
    FOREIGN KEY (`obrazek_idObrazek`)
    REFERENCES `wikipedie`.`obrazek` (`idObrazek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obrazek_has_stranka_stranka1`
    FOREIGN KEY (`stranka_idStranka`)
    REFERENCES `wikipedie`.`stranka` (`idStranka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
